#!/usr/bin/env bash

echo "Creating an Apps directory on your Desktop ..."
  mkdir ~/Desktop/Apps
  cd ~/Desktop/Apps

echo "Downloading a script that finds the latest downloads for your apps ..."
  curl -Os https://raw.github.com/molawson/laptop/master/lib/latest_release.rb

echo "Installing the Mechanize gem that helps find the latest downloads for your apps ..."
  gem install mechanize --no-ri --no-rdoc

echo "Downloading Dropbox ..."
  curl -Ls https://www.dropbox.com/download?plat=mac > Dropbox.dmg

echo -e "This would be a good time to setup Dropbox so it can start downloading your files.\nWould you like to do that now? [y/n]"
read x
if [ $x == "Y" -o $x == "y" ] ; then
  open ~/Desktop/Apps/Dropbox.dmg
  echo -e "Press ENTER to continue."
fi

echo "Downloading 1Password ..."
  curl -Os "$(ruby latest_release.rb one_password)" 

echo "Downloading Alfred ..."
  curl -Os "$(ruby latest_release.rb alfred)" 
  
echo "Downloading Carbon Copy Cloner ..."
  curl -Ls http://www.bombich.com/software/download_ccc.php > ccc.dmg

echo "Downloading Firefox ..."
  curl -Os "$(ruby latest_release.rb firefox)" 

echo "Downloading GitX ..."
  curl -Os http://frim.frim.nl/GitXStable.app.zip

echo "Google Chrome needs to be downloaded from a web browser.\nWould you like to do that now [y/n]"
read y
if [ $y == "Y" -o $y == "y" ] ; then
  open https://www.google.com/chrome/
  echo -e "Press ENTER to continue."
fi

echo "Downloading MockSMTP ..."
  curl -Ls http://mocksmtpapp.com/download > MockSMTP.zip

echo "Downloading Propane for Campfire ..."
  curl -Os http://propaneapp.com/appcast/Propane.zip

echo "Skype needs to be downloaded from a web browser.\nWould you like to do that now [y/n]"
read z
if [ $z == "Y" -o $z == "y" ] ; then
  open http://www.skype.com/go/downloading
  echo -e "Press ENTER to continue."
fi

echo "Downloading Spotify ..."
  curl -Os http://download.spotify.com/Spotify.dmg

echo "Downloading Transmit ..."
  curl -Os "$(ruby latest_release.rb transmit)" 
  
echo "Cleaning up ..."
  rm latest_release.rb
