#!/usr/bin/env bash

echo "Creating an Apps directory on your Desktop ..."
  mkdir -p ~/Desktop/Apps
  cd ~/Desktop/Apps

echo "Downloading a script that finds the latest downloads for your apps ..."
  curl -Os https://raw.github.com/molawson/laptop-apps/master/lib/latest_release.rb

echo "Installing the Mechanize gem that helps find the latest downloads for your apps ..."
  gem install mechanize --no-ri --no-rdoc

echo "Downloading Dropbox ..."
  curl -Ls https://www.dropbox.com/download?plat=mac > Dropbox.dmg

echo "This would be a good time to setup Dropbox so it can start downloading your files."
read -p "Would you like to do that now? [y/n] " dropbox
if [ $dropbox == "Y" -o $dropbox == "y" ] ; then
  open ~/Desktop/Apps/Dropbox.dmg
  read -p "Press ENTER to continue. " cont
fi

echo "Downloading 1Password ..."
  curl -Os "$(ruby latest_release.rb one_password)" 

echo "Downloading Alfred ..."
  curl -Os "$(ruby latest_release.rb alfred)" 
  
echo "Downloading Carbon Copy Cloner ..."
  curl -Ls http://www.bombich.com/software/download_ccc.php > ccc.dmg

echo "Downloading Firefox ..."
  curl -Os "$(ruby latest_release.rb firefox)" 

echo "Downloading GitX ..."
  curl -Os http://frim.frim.nl/GitXStable.app.zip

echo "Google Chrome needs to be downloaded from a web browser."
read -p "Would you like to do that now [y/n] " chrome
if [ $chrome == "Y" -o $chrome == "y" ] ; then
  open https://www.google.com/chrome/
  read -p "Press ENTER to continue. " cont
fi

echo "Downloading MockSMTP ..."
  curl -Ls http://mocksmtpapp.com/download > MockSMTP.zip

echo "Downloading Propane for Campfire ..."
  curl -Os http://propaneapp.com/appcast/Propane.zip

echo "Skype needs to be downloaded from a web browser."
read -p "Would you like to do that now [y/n] " skype
if [ $skype == "Y" -o $skype == "y" ] ; then
  open http://www.skype.com/go/downloading
  read -p "Press ENTER to continue. " cont
fi

echo "Downloading Spotify ..."
  curl -Os http://download.spotify.com/Spotify.dmg

echo "Downloading Transmit ..."
  curl -Os "$(ruby latest_release.rb transmit)" 
  
echo "Cleaning up ..."
  rm latest_release.rb
